"""Initial migration.

Revision ID: 7b88cbd968ff
Revises: 
Create Date: 2024-06-28 09:28:42.772305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b88cbd968ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=100), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('forma_envio', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura')
    # ### end Alembic commands ###
